name: movil_educontrol
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  qr_code_scanner: ^1.0.0
  intl: ^0.17.0
  permission_handler: ^11.3.1
  universal_html: ^2.0.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/background_leaves.jpg
    - assets/success_ghost.svg
    - assets/failed_ghost.svg