name: movil_educontrol
description: "EDUCONTROLMOBILE"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Actualizamos para ser compatible con `http 1.1.1`

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0  # Podrías intentar con `^1.2.2` también si el problema persiste
  flutter_svg: ^2.0.10+1
  qr_code_scanner: ^1.0.0
  intl: ^0.17.0
  permission_handler: ^11.3.1
  universal_html: ^2.0.6
  cupertino_icons: ^1.0.6
  sentry_flutter: ^8.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  build_runner: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_leaves.jpg
    - assets/success_ghost.svg
    - assets/failed_ghost.svg
